---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1865qkpljna6my0wj8xza06x4f65hswshn7ex864zs48pajjeh4fsaz66pu
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1865qkpljna6my0wj8xza06x4f65hswshn7ex864zs48pajjeh4fsaz66pu
  - path_regex: terraform/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1865qkpljna6my0wj8xza06x4f65hswshn7ex864zs48pajjeh4fsaz66pu
