apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:CIaqUAtZ0pbx1YoecHdviw==,iv:TRHLEn7zwdWqr/kRJbMttQsQ5WXcJwfS8xR6Q9wEjsg=,tag:0UkU7rFUW6XatvLBP7uMXQ==,type:str]
    api-key: ENC[AES256_GCM,data:gAghaYkCCStDaDzccItyM+A6Brqf2lm5668by+AIhfxRjBlP2g==,iv:NpYovz0bxFQjiISar1Hl2uzLv9vnowuqunt47HbgBRw=,tag:LYw/AIUNVxsEkM8RQ4yYDg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1865qkpljna6my0wj8xza06x4f65hswshn7ex864zs48pajjeh4fsaz66pu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2S0JHbE1mZXVPbUxtZ012
            Y2xKeUk4ZE03RmxRNWJ1VlB0dVBvRTJKN3pjCmh3a3hOV3I1TjNVRWg5Yi9NSXpF
            ZEMydWJ5U3lzNk5PRkQ2WG04ekNsQWsKLS0tIFhpS3FPeU9rU0dBM0dReHRDaFBm
            TEY2NXhhSyt0N0xoUlhyaFlwd3RpWTAKvoWAbc059xukjUFQhXNh6bnl0vFd+hr6
            uIjXDpbm5DXKtXBdpp5ly7p/uhJVeA/bL1hdB34CTfrJOk5CdQLKzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-03T12:22:06Z"
    mac: ENC[AES256_GCM,data:D3Or6JmgvBMCtSOH3puv9srU+wU/xoIzeuqDGoQ31IBXJP4ErgZcgwOwb4SgElQcZ7K+1jVPhyImcuh+4z62ovnqJWCSqYjLNBcSJhinQXB2s/ufv3MX5P2smrCdyReJYLNYXZeKKME7dTGqp347fbMocd0pXMmj6v+T6lP6djw=,iv:4eQiacOUViVNdjKDerOuAczmlKzcpjNeTah198LLD1c=,tag:PILYo6KBlp/ZFvfPHy9L6g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
