apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:eSQ0KFfZUuz9FtJFbT9lC7fvFHprFzzrkGsb9rn1X++RbO8d2pcpWZPCaQKhzcgUZVUPO1NWh9Jkprxo,iv:niGQ6aZu6mE1eSCZ93y2Yam6tuZSNjjUsV6VKe+Di8k=,tag:3a1/329bwUCrH9kiSWKEhg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1865qkpljna6my0wj8xza06x4f65hswshn7ex864zs48pajjeh4fsaz66pu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAybDVseFJqNmNvU3Y5WTdN
            RWIzb2FNWEpFeGpsWlFLbGx0RlUyNE01dndRCkF5cExIR0I2ajEwNkJ4VFVBWm5W
            OU9NMzZtdGJWaFpXeEdMTTc0Szltc2sKLS0tIEFnRjJVdWZWcWVoL3VReFRsNUdO
            Mm9XS2plVjVDWkdPbEI5MmRLRXBjU0kK8MYsMgrCVofqXBJ8/p3PBPJ04aAWRgw5
            BbfrMQPuUKYurg/iCwM4668P/0vV/9erwkvnpRsKhQt8mUvf1s7isg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-03T12:22:10Z"
    mac: ENC[AES256_GCM,data:u0Y3tBY7P4t/mp4Jppx5kW4DNUfBWq9z3twox0ovuz7ZqWtwq9qxaVa360IeSFKZUW8Uz1zITcw041nn3RCLbVF32Jl85wIthbl5H4H/x1P+VuoQL3d98fNLwfozCNuCfRu9H3wsyCWa4H7mYjVoEJk1Bs7Pa+rA6tV3QYmbrJU=,iv:5q3qU3ILXW4lxToFFOWl3A2tM8Kn3x+lpptGz37keew=,tag:Vmc5ophys5ouHeAx6shLnw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
