---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Amsterdam"
  KUBE_VIP_ADDR: "192.168.0.99"
  METALLB_LB_RANGE: "192.168.0.150-192.168.0.200"
  METALLB_K8S_GATEWAY_ADDR: "192.168.0.150"
  METALLB_INGRESS_ADDR: "192.168.0.200"
